framework:
    secret: '%env(APP_SECRET)%'
    default_locale: 'en'
    translator:
        fallbacks: ['en']
    session:
        handler_id: ~
    esi: true
    templating:
        engines: ['twig']
    fragments: { path: /_fragment }
    php_errors:
        log: true
    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'