lexik_jwt_authentication:
  private_key_path: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
  public_key_path: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
  token_ttl: 3600
  encoder:
    signature_algorithm: HS256
    service: lexik_jwt_authentication.encoder.lcobucci
  token_extractors:
    cookie:
      enabled: true
      name: token