security:
    access_denied_url: /login
    encoders:
      Symfony\Component\Security\Core\User\User:
        algorithm: bcrypt
        cost: 12
    providers:
      in_memory:
        memory:
          users:
            admin:
              password: $2y$12$R.XN53saKaGFZ5Zqqpv5h.9NzwP0RH4VlEGmRryW1G3cM3ov1yq32
              roles: 'ROLE_ADMIN'
    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
      main:
        anonymous: true
        stateless: true
        form_login:
          check_path:               /login
          success_handler:          App\Security\JwtAuthenticationSuccessHandler
          failure_handler:          App\Security\JwtAuthenticationFailureHandler
        guard:
          authenticators:
            - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/private, roles: ROLE_ADMIN }